# Generated by Django 5.0.6 on 2024-08-06 09:25

from django.db import migrations


# Set up default roles
# IMPORTANT: Change this if additional roles are added
def populate_roles(apps, schema_editor):
    Role = apps.get_model("login", "Role")
    Role.objects.bulk_create(
        [
            Role(role_id=1, role="Admin"),
            Role(role_id=2, role="Student"),
            Role(role_id=3, role="Instructor"),
            Role(role_id=4, role="Trainer"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_roles)]
