# Generated by Django 5.0.6 on 2024-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_verificationotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationotp",
            name="time_sent",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
