# Generated by Django 5.0.6 on 2024-08-06 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseEnrollments",
            fields=[
                (
                    "enrollment_number",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_enrolled", models.DateTimeField(auto_now=True)),
                ("price_at_enrollment", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CourseReviews",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField(max_length=255)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("material_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.TextField()),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "pdf"),
                            ("docx", "docx"),
                            ("ppt", "ppt"),
                            ("mp4", "mp4"),
                        ],
                        max_length=4,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ViewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.IntegerField()),
                ("view_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("start_date", models.DateField(auto_created=True)),
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=100)),
                ("reference_num", models.IntegerField(null=True)),
                ("price", models.FloatField()),
                ("description", models.TextField(max_length=255)),
                ("categories", models.ManyToManyField(to="LMS.category")),
            ],
        ),
    ]
