# Generated by Django 5.0.6 on 2024-08-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover_img",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="trailer",
            field=models.TextField(null=True),
        ),
    ]
