# Generated by Django 5.1 on 2024-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0003_course_cover_img_course_trailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursereviews",
            name="created_at",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
