# Generated by Django 5.1 on 2024-08-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0004_alter_coursereviews_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
    ]
